[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"


[project]
name = "inventory-allocation-system"
version = "0.1.0"


[tool.setuptools]
py-modules = ["config"]


[tool.setuptools.packages.find]
include = ["app*", "tests*"]


[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]